title: Computer Science (CS) @ Jetzt Gov
description: Computer Science (CS) @ Jetzt Gov

breadcrumbs: true 

titles_from_headings:
  enabled: true
  strip_title: true
  
remote_theme: jekyll/minima
minima:
  skin: solarized

header:
  teaser: my-awesome-post-teaser.jpg


author:
  name   : Saqib Ali
  avatar : "bio-photo.jpg"  # placed in /images/
  bio    : Computer Scientist
  email  : docbook.xml@gmail.com
  uri    : https://qosf.com

